@apiUrl = http://localhost:5000/api

# ================= AUTH ======================= #

### LOGIN
POST {{apiUrl}}/auth/login
content-type: application/json

{
  "email": "sample.email@address.pl",
  "password": "wiezA123"
}

### REGISTER
POST {{apiUrl}}/auth/register
content-type: application/json

{
  "name": "Łukasz K.",
  "email": "sample.email@address.pl",
  "password": "wiezA123"
}

### LOGOUT
POST {{apiUrl}}/auth/logout

# ================= PARTNERS ======================= #

### GET all
@deletedPartners = 0
// @name partners
GET {{apiUrl}}/partners?withDeleted={{deletedPartners}}

### GET one
// @name partner
GET {{apiUrl}}/partners/{{partners.response.body.$.[0].id}}

### CREATE
// @name partner
POST {{apiUrl}}/partners
content-type: application/json

{
  "name": "ABC Company",
  "taxNumber": "78912311222",
  "address": {
    "street": "Some street",
    "city": "Some city"
  }
}

### UPDATE
// @name partner
PUT {{apiUrl}}/partners/{{partners.response.body.$.[0].id}}
content-type: application/json

{
  "name": "ABC Company {{$randomInt 1 20}}",
  "taxNumber": "78912311221"
}

### DELETE
DELETE {{apiUrl}}/partners/{{partner.response.body.$.id}}

# ================= INVOICES ======================= #

### GET all
@deletedInvoices = 1
// @name invoices
GET {{apiUrl}}/invoices?withDeleted={{deletedInvoices}}

### GET one
// @name invoice
GET {{apiUrl}}/invoices/{{invoices.response.body.$.[0].id}}

### CREATE
// @name invoice
POST {{apiUrl}}/invoices
content-type: application/json

{
  "number": "01/12/2019",
  "invoiceDate": "{{$datetime iso8601}}",
  "paymentDate": "{{$datetime iso8601 10 d}}",
  "partnerId": "{{partner.response.body.$.id}}",
  "invoiceItems": [
    {
      "name": "item 1",
      "quantity": {{$randomInt 1 6}},
      "unitPrice": "{{$randomInt 5 55}}.{{$randomInt 0 100}}"
    },
    {
      "name": "item 2",
      "quantity": {{$randomInt 2 10}},
      "unitPrice": "{{$randomInt 1 35}}.{{$randomInt 0 100}}"
    }
  ]
}

### DELETE
DELETE {{apiUrl}}/invoices/{{invoice.response.body.$.id}}
