@apiUrl = http://localhost:5000/api

# ================= AUTH ======================= #

### LOGIN
POST {{apiUrl}}/auth/login
content-type: application/json

{
  "email": "sample.email@address.pl",
  "password": "wiezA123"
}

### REGISTER
POST {{apiUrl}}/auth/register
content-type: application/json

{
  "name": "Łukasz K.",
  "email": "sample.email@address.pl",
  "password": "wiezA123"
}

### LOGOUT
POST {{apiUrl}}/auth/logout

# ================= PARTNERS ======================= #

### GET all
// @name partners
GET {{apiUrl}}/partners

### GET one
// @name partner
GET {{apiUrl}}/partners/{{partners.response.body.$.[0].id}}

### CREATE
// @name partner
POST {{apiUrl}}/partners
content-type: application/json

{
  "name": "ABC Company",
  "taxNumber": "7891231122",
  "address": {
    "street": "Some street",
    "city": "Some city"
  }
}
