@apiUrl = http://localhost:5000/api

### Hello
GET {{apiUrl}}/hello

### Hello POST
POST {{apiUrl}}/hello
content-type: application/json

{
  "firstName": "Łukasz",
  "lastName": "K."
}

# ================= AUTHORS ======================= #

### GET all
// @name authors
GET {{apiUrl}}/authors

### GET one
// @name author
GET {{apiUrl}}/authors/{{authors.response.body.$.[0]._id}}

### CREATE
// @name author
POST {{apiUrl}}/authors
content-type: application/json

{
  "fullName": "Stephen King"
}

### UPDATE
// @name author
PUT {{apiUrl}}/authors/{{author.response.body.$._id}}
content-type: application/json

{
  "fullName": "Stephen Edwin King"
}

### DELETE
DELETE {{apiUrl}}/authors/{{author.response.body.$._id}}

# ================= BOOKS ======================= #

### GET all
// @name books
GET {{apiUrl}}/books

### GET one
// @name book
GET {{apiUrl}}/books/{{books.response.body.$.[0]._id}}

### CREATE
// @name book
POST {{apiUrl}}/books
content-type: application/json

{
  "title": "Doctor Sleep",
  "authorId": "{{author.response.body.$._id}}"
}

### UPDATE
// @name book
PATCH  {{apiUrl}}/books/{{book.response.body.$._id}}
content-type: application/json

{
  "title": "Doctor Sleep {{$randomInt 0 100}}"
}

### DELETE
DELETE {{apiUrl}}/books/{{book.response.body.$._id}}

# ================= BOOKS ======================= #

### LOGIN
POST {{apiUrl}}/auth/login
content-type: application/json

{
  "email": "test@test.pl",
  "password": "wiezA123"
}

### REGISTER
POST {{apiUrl}}/auth/register
content-type: application/json

{
  "name": "Łukasz K.",
  "email": "sample.email@address.pl",
  "password": "wiezA123"
}
